### ISSUE TITLE
Not saving+other

### ISSUE THREAD

**Issue by A1C6** [r3eckon/BNG-BeamLegalRacing#1]
If I completely close the game it doesn't save my data for some reason. 
I also attempted to mod the BeamLR/mainDATA file with no results.
Also which file to you copy over the update (suggested file couldn't be found).
The traffic is also extremely reckless. On one drive on the highway I saw 4 crashes, in one of which someone drove into me.

**NOT ISSUES - SUGGESTIONS BELLOW**
Wouldn't it be good to be able to modify your car without completely fixing it? I understand this would be hard but it would be AWSOME.

**Comment by r3eckon** [comment]
Hi and thanks for the issue report, if you have mods enabled first disable them and try again to see if another mod is causing problems. 

Also, please be more specific. Do you mean if you close BeamNG completely your save resets but not if you stay in? What data didn't save and how did you close the game? The scenario has no autosave feature, data is currently saved when you abandon the scenario, when you win races, etc. If you ALT+F4 out of the game you will lose progress.

What do you mean by attempting to mod the mainData file? Did you try to add money? If you make changes to this file you need to restart the scenario for them to take effect. It should be very simple to just open the mainData file with notepad, add a bunch of zeros to the initial value of 20 so that it reads money=200000 or whatever then save that file and load into the mission again to see the hacked value.

For update it should be simple to follow the instructions on your type of install. For now you need to replace everything except the beamLR folder. With the modder install you drag and drop all the updated folders in your userfolder. The OS will ask what you want to do with existing stuff. Tell the OS to replace existing files. This is how they are updated.

I wish I could add your suggestion but that's not up to me sadly. You need to ask the BeamNG devs to add that in the game. I tried many workarounds and nothing works, the car is always reset when editing parts.

**Comment by A1C6** [comment]
Thankyou for your quick, lengthy and kind response.
Also please don't be insulted it I report stuff in the future, I just want this the best it can be!

**Comment by r3eckon** [comment]
I hope you didn't get the impression that I'm insulted by bug reports lol I know the mod is very unstable for now, on the contrary I'm glad that some people care enough to report issues instead of just quitting and never reporting problems. 

That being said I need bug reports to be very precise, with steps to reproduce, even better if you can include as much information as possible, screenshots, video, etc. It's very time consuming to chase bugs with little information to know where to start looking. When you say you attempted to mod the mainData file with no result I can't know what you tried so that's why I ask for details.

Please don't hesitate to report other issues you experience! Just make sure to be precise when you do so that I can help.

**Comment by r3eckon** [comment]
Also if you think the install instructions are confusing please let me know, when I say it should be simple what I mean is I hope it's simple enough to do, but the documentation and instructions are very barebones and I haven't had the time to improve them yet since I got a ton on my plate already. If you think they could be more clear that's good feedback for me to have.

**Comment by A1C6** [comment]
I understand, thanks!
