### ISSUE TITLE
Cannot start track events (Utah, 1.12)

### ISSUE THREAD

**Issue by Polaria1** [r3eckon/BNG-BeamLegalRacing#11]
Whenever I go to the track events menu and click on a compatible event where my car passes inspection (and I have the money and reputation to start it), the game claims that I "already joined another event" despite never having done so. I've loaded up all of the tracks that I can think of in the game which have track events and upon loading them there is nothing. I am not in staging for a street race or being chased by the police; I honestly have no idea what's going on. Maybe I'm misunderstanding how it works? Either way I feel like this should be pointed out.
![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/63474085/37f007ba-f8c8-4494-adc6-396715efec91)

**Comment by r3eckon** [comment]
I've had another report about this on the forum, see the below post for workarounds. The second one where you replace the **efile** line of the **beamLR/currentTrackEvent** file seems to have worked for another user so try that first. The issue is probably caused because that file by default points to the Nordschleife track event which is weird as the mod seems to properly detect that you don't have the map installed because it's not offered in the event list.

https://www.beamng.com/threads/beam-legal-racing-slrr-inspired-hardcore-career-mod.87394/page-30#post-1621039

**Comment by r3eckon** [comment]
Update, I have fixed this bug for hotfix 12.1 which should release soon. The issue was caused by a function trying to look up the name of the map before checking if the map is installed, which prevented the join state data from being passed to the UI.

**Comment by Polaria1** [comment]
Alright, thank you! Late response I know but I do appreciate the fix
