### ISSUE TITLE
2nd gen pessima missing center lug wheels

### ISSUE THREAD

**Issue by LemonXVI** [r3eckon/BNG-BeamLegalRacing#12]
Bought and fit the center lug hubs on a 2nd gen pessima and there seems to be no wheel options available in the part store and no default wheels given to the car. All the necessary suspension components are installed.
![pesswh](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/52186642/7d6c72a7-58ee-4f45-a820-af97e267e4c8)

I think I also had this issue before with a covet but don't currently have one in this save to check.

**Comment by r3eckon** [comment]
It also happens in freeroam so this isn't due to a bug with BeamLR, the jbeam files for center lug hubs have a typo, the default part name is incorrect and basically doesn't exist. Size should be 19x8 not 19x9.

This is from the pessima hub jbeam with incorrect 19x9 size:
![](https://i.imgur.com/2xXOLIo.png)

This is the actual part jbeam which has the correct 19x8 size:
![](https://i.imgur.com/GFmMvgE.png)

This should be reported in the 0.30 discussion thread so devs can fix it. I'm not sure how the vanilla part editor shows the slot given it's missing from available parts list, could be some extra steps the vanilla part editor goes through that manages to find the slot despite the error.

To fix it yourself create the folder **userfolder/vehicles/midsize/** if it doesn't already exist. Then from the game's steam files open up **content/vehicles/midsize.zip** and extract these two files inside the folder you created:

![](https://i.imgur.com/2eZCb2G.png)

Finally open up both files and fix the incorrect sizes, basically:
Replace **centerlug_wheel_01a_19x9_R** and **centerlug_wheel_01a_19x9_F** 
With **centerlug_wheel_01a_19x8_R** and **centerlug_wheel_01a_19x8_F**

Like you said the covet has the same bug so you can repeat the process with the covet to fix it.
