### ISSUE TITLE
Pressing abandon while looking at a car in the shop breaks the save

### ISSUE THREAD

**Issue by Krakon01** [r3eckon/BNG-BeamLegalRacing#13]
If I visit a car shop, look at the cars that are available to buy and decide to quit BeamLR and go back to freeroam then load BeamLR , no vehicle spawn for me and I cannot do anything.

**Comment by r3eckon** [comment]
Basically the scenario saves vehicle related data using player vehicle ID and while browsing shops that ID changes leading to mismatch between main garage file car model and saved config values. 

Since I would have had to modify the vanilla partmgmt.lua script to allow saving configs on a vehicle other than the current player vehicle I instead added a simple flowgraph check after pressing abandon. While browsing a car shop that check prevents the usual save process from happening and will inform the player they need to exit the vehicle shop before quitting. 

Thanks for the issue report! Until I release 1.13 you should avoid quitting while browsing vehicle shops.
