### ISSUE TITLE
Probably some beamstate issues.

### ISSUE THREAD

**Issue by abodyeasy** [r3eckon/BNG-BeamLegalRacing#19]
I really like the new update especially the new option for better repair cost, but I had some problems when I had let's say 3 cars in the garage, and crashed one of the cars and wanted to change it to the other car it somehow breaks the car when I spawn it, or sometimes when I change back to the crashed car, the repair cost gets to a crazy number like 30k or something, and sometimes when I load the crashed car again it repairs itself, is this a normal issue? or am I doing something wrong? Overall the mod is so good so far with all the updates, and I'm considering making this a YouTube series for people to see :) I just want it to be perfect so there are no issues and I will definitely start making some videos, but I appreciate your work 🙏

**Comment by abodyeasy** [comment]
Oh and also when i tried to play it earlier it stuck on the loading screen, probably because of the new 0.31 update :)

**Comment by r3eckon** [comment]
The mod is broken on 0.31 it will be fixed when I release next update. 

About your first issues, please give me more details. Are you playing with beamstate enabled? Since BeamNG 0.28 beamstate is broken and there's nothing I can do about it, it's on the known issues list for the game but devs haven't managed to fix it yet. If you are playing with beamstate enabled you should disable it for now.

**Comment by abodyeasy** [comment]
Yeah i enabled beamstate, but i think even when it's disabled it somehow makes the repair cost 30k or something, i have to try the mod again to see the problem but i'm gonna wait for the next update, for now you can close this issue if you want :)

**Comment by r3eckon** [comment]
If you switched cars after the 30k damage happened it'll save that damage value to the vehicle file, you can open them and manually revert that value to 0 and without beamstate enabled it shouldn't take any damage. Leave the issue open for now, after next update releases see if it happens without beamstate and let me know.

**Comment by abodyeasy** [comment]
Sorry for the late response, I just tried the mod, and there is this one issue where if I total my starter car or any other car, and switch the car again, the repair cost somehow resets to 0, is this fixable?

**Comment by abodyeasy** [comment]
Looks like the issue is with the Advanced Cost System, which is the best feature in the mod, is it fixable? or is it just a complicated issue?

**Comment by r3eckon** [comment]
Thanks for the report, I fixed it by sending the vehicle's saved damage value to the advanced repair UI and using it as the minimum value for the advanced repair cost just like the old repair cost calculation system works. Sadly until BeamNG devs fix beamstate loading there's no way I can reload the actual damage that's saved in beamstate only mechanical damage like broken engine, broken radiator, etc. My best option is to store repair cost and use it as a minimum which, when beamstate works, helps to counteract the changing damage values from beamstate loading not being 100% accurate to what the beam deformation values were upon saving. 

Long story short it will show up as "Saved Damage Fee" in the advanced repair menu and the displayed fee will be offset by parts you choose to repair to keep the total repair value at that saved minimum unless you select parts that cause the repair cost to be above the minimum.

Here the saved damage is $132.05, since the "Wagon Body" part can't be unselected that 7 cents is removed from the fee so the total repair cost is still the $132.05 minimum value stored in the vehicle file:

![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/5762743/9e21d5df-bde6-47fa-9983-bf8907622e4d)

If I select enough parts so that the repair cost is now above that minimum value, the fee isn't shown:

![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/5762743/3d50e74e-4124-4143-89d2-60f967b98e5b)

**Comment by abodyeasy** [comment]
Thank you so much for fixing that, hopefully the devs will actually fix the beamstate problems, until then we'll wait patiently for the next updates :)
