### ISSUE TITLE
Loading screen issue, some suggestions.

### ISSUE THREAD

**Issue by abodyeasy** [r3eckon/BNG-BeamLegalRacing#24]
After the new update, I always get the loading screen issue when I abandon BeamLR and start BeamLR again, I get a black screen just like in the picture I uploaded, but it gets fixed when I sleep, it probably resets the UI. Suggestion: It would be better if the GPS had some locations like the Drag races and other races, as well as the Scrapyard. Another Suggestion: Adding the feature to go to a hospital or pharmacy to refill health instead of sleeping, because you can easily refill your health if you just sleep for 1 hour, i'm not sure if the health even works, but when I crashed going 120 Mph, I died and reset the career, which makes it scarier and better, thanks. 
![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/65369877/1b730ecb-74b8-4dc5-9449-a02ced03ed62)

**Comment by r3eckon** [comment]
I can't seem to recreate the loading screen issue. That screen was changed in a BeamNG update and needs the "Fade From Black" node to go away which happens when the scenario starts so I don't know why it doesn't work for you when it works for me but I have suspicions it could be caused by some sort of race conditions between the scenario start and the loading screen UI. 

If you can I'd like you to test a fix for me, because I can't test it if I don't get the issue.

1. Download this [edited mission file](https://github.com/r3eckon/BNG-BeamLegalRacing/files/13945812/project.flow.json)
2. Use it to replace this file : **userfolder/gameplay/mission/BeamLegalRacingUtah/project.flow.json**
3. Restart BeamNG if it was running then try whatever caused the issue to see if it was fixed. 

Then just let me know if the fix worked. If it does work and you have enough time I'd like you to try something else. Basically the fix is just adding some delay before using "Fade From Black" but that delay should be reduced as much as possible. If the fix didn't work you could also try these steps but adding delay instead of removing it to see it that gets it working.

1. Open BeamNG world editor (F11)
2. Open the Flowgraph Editor (Top Bar > Window > Gameplay > Flowgraph Editor)
3. Load the flowgraph file (Flowgraph Editor Top Bar > File > Load Project) located at **gameplay/mission/BeamLegalRacingUtah/project.flow.json**

From that point on the editor will be extremely laggy so when you click or hit keys try going super slow like keep the key pressed in for longer than you would normally otherwise it might not register. I really mean it, if you don't go slow enough the edits you make might end up not being saved.

4. Look around to find the big area labeled "Fatal Accident Detector"
5. Click on the "Frame Delay" node pointed in the below image

![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/5762743/5705ed5e-f23a-4f3a-927e-0d5026c54eff)

6. On the left of the Flowgraph Editor the node properties will appear, reduce the amount of "frames" by half

![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/5762743/28b34dd5-d994-4977-82b4-3d4ecbf5f3af)

7. Click on "States" to gain back FPS for the next part to be easier

![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/5762743/0fa87cb6-1844-497e-b8cd-bfd800edd248)

9. Save the project ( Flowgraph Editor Top Bar > File > Save )
10. Close the world editor and restart BeamNG

Try recreating the issue again, if it doesn't happen, repeat the process and keep halving the amount of frames in step 6 until the bug happens. If you get to 1 frame and the issue still doesn't happen you can stop there. Let me know at which point the issue happened if at all. I understand this may be a bit time consuming so if you're feeling lucky you could set it to 1 frame on first try and if that doesn't work do a gradual decrease from 30.

**Comment by abodyeasy** [comment]
I tried the edited mission file, but unfortunately it didn't make a difference, then i did the F11 fix and i got an issue when i tried editing the fatal crash frames, it's gray for me for some reason.
![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/65369877/cf9ef8da-0c3e-424b-81eb-35f675e76f1c)
Also i am playing on East Coast, and the edited file is Utah, does it make a difference? i'm very bad at coding lol.

**Comment by r3eckon** [comment]
If you replaced the file in the folder I specified then you need to be on utah to launch the edited mission file. Also this graying out happens when you launch the mission from the blue marker, it should come back to normal if you load a different flowgraph project (like the one in gameplay/mission/BeamLegalRacingEastCoast) then load back into the previous one, or just restart the game.

**Comment by abodyeasy** [comment]
Sorry for taking too long to respond, Sadly I tried to reduce the frames to 2 going to 9 and unfortunately no luck, but maybe in the next update I will reinstall the mod because maybe there could be problems with the installation. I'm not sure, but overall I'm manging to make the sleeping at 0.5, and every time I join the game I just simply sleep, and then the black screen will just disappear.

**Comment by r3eckon** [comment]
Try this in lua console instead of sleeping `ui_fadeScreen.stop(1)`

**Comment by abodyeasy** [comment]
It worked thanks!

**Comment by r3eckon** [comment]
Since the command works delay should also solve that problem, it's just a matter of finding the correct amount of delay. I'll add an option to tweak the amount so you don't have to edit flowgraph, might be useful to other players having the same issue.
