### ISSUE TITLE
nordslchiefe track events not working

### ISSUE THREAD

**Issue by Real-Racing-Rookie** [r3eckon/BNG-BeamLegalRacing#26]
when i load in all I get is a camera looking at the track as if there wasn't the car and the event loader saying null.
![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/124314510/11accf10-c008-4caf-9c4a-b3474208059e)

**Comment by r3eckon** [comment]
This will be fixed in next update for the addon, I fixed it for vanilla map events but forgot to update the addon mission file. You should be able to fix it by creating a file called "playerName" inside the beamLR folder, add the name to show up on the event leaderboard.

**Comment by r3eckon** [comment]
This should now be fixed with latest version of the addon.

**Comment by Real-Racing-Rookie** [comment]
![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/124314510/cac2aad0-3a1c-45b6-9c44-755b201576fb)
it now loads in but the AI is not moving anywhere

**Comment by r3eckon** [comment]
You most likely have a ks_nord folder in **userfolder/levels**. The addon zip file has edits needed for this track event to work. That folder overwrites my changes as the levels folder has priority over zipped mods. If you want to keep whatever changes were contained in the folder just move it elsewhere, otherwise just delete it.
