### ISSUE TITLE
Split flowchart using subcharts

### ISSUE THREAD

**Issue by unai-ndz** [r3eckon/BNG-BeamLegalRacing#3]
I have a beefy computer and opening the flowchart of this mod drops me to 6 fps. I have around 15 min tinkering with it but looks like it can be split into subcharts. Thoughts?

**Comment by A1C6** [comment]
What flow chart?

**Comment by r3eckon** [comment]
I might experiment with subgraph at some point but this is not high priority for now as project size doesn't impact performance while playing, it's just annoying while making changes to the flowgraph. Many features of FG are buggy so I'm sure this would break a couple things. Thanks for the suggestion, I'll keep this in mind.

**Comment by unai-ndz** [comment]
I did some testing. Just select all the components you want to move into the subgraph > right click and create subgraph. It keeps the position of the nodes in the new one and handles the inputs/outputs automatically. 

But you were right, unless I fucked something in the process these changes made the mission UI do not reset after refusing one mission.

![image](https://user-images.githubusercontent.com/29188654/211279645-6734a631-3a41-4d8c-bca5-dd36a61d7421.png)

Player Garage

![image](https://user-images.githubusercontent.com/29188654/211278519-13f64b3e-5132-476b-bb8c-cfa3531b5723.png)
![image](https://user-images.githubusercontent.com/29188654/211278833-f43d855f-f356-4b73-a3f4-31e066b8022b.png)

**Comment by r3eckon** [comment]
Did it improve FPS in editor? Also not surprising that it breaks things.

I'm not sure what precisely causes FG editor to slow down with massive projects but I'm pretty sure lines rendering have something to do with it since hiding them improved framerate a tiny bit back when I was getting around 15 FPS.  But this feature is also bugged and makes it so areas of the graph won't register clicks on visible links. 

If it's a rendering problem some sort of basic 2D occlusion would be a great addition to FG, I don't mind low FPS when zoomed way out but it shouldn't lag that hard when zoomed in with a small amount of nodes in view.

**Comment by unai-ndz** [comment]
Sorry I missed your comment.

Yes it improves fps dramatically, from ~10 to 60 fps. And the less nodes the better.

Its not taxing on the gpu at all, if I remember correctly it was pegging one CPU core almost all the time. The moment I closed the editor both CPU and GPU started getting used properly.

**Comment by r3eckon** [comment]
That's good to know, sounds like FG editor could be optimized a bit by the devs. I'll check if I can get it to work using subgraphs in a future update.
