### ISSUE TITLE
Engine problem

### ISSUE THREAD

**Issue by joninh4** [r3eckon/BNG-BeamLegalRacing#53]
Every time I change the engine of my car, I can't put the intake or the engine block, it only shows this error, I don't think it's a problem with BeamNG because I saw some videos and the youtubers can change the engine without any problems. I've reset my career about 5 times and this error always appears the same way, I buy the car, change the engine, buy an intake and the engine block and when it's time to put it in, the same error appears. This error doesn't only appear with the engine, but also with the wheels.
![issue](https://github.com/user-attachments/assets/7ff7c3b3-6029-46f2-b7ff-d1933270a900)

**Comment by r3eckon** [comment]
Post logs.

**Comment by joninh4** [comment]
But my game don't crash, only show thir error, Idk where I can find these logs that only shows this error but I'll try to send some of them. These logs that I'm sending are the last logs that have been created
[beamng.log](https://github.com/user-attachments/files/17101715/beamng.log)
[beamng.2.log](https://github.com/user-attachments/files/17101716/beamng.2.log)

**Comment by r3eckon** [comment]
Mod isn't installed correctly, you're not supposed to put the zip file in the mods folder. That can cause all sorts of issues. Follow step 3 of the troubleshooting guide, which you should go through before reporting issues. I specifically added a message about this in the issue creation form.

Since your save files might be broken don't bring them back, cheat yourself money by editing the mainData file and rebuild the cars you had. If you get the issue again, reopen the issue and attach the new log files.
