### ISSUE TITLE
Spawn issue

### ISSUE THREAD

**Issue by maksimkfive** [r3eckon/BNG-BeamLegalRacing#7]
Hello! Your project is amazing and interesting af! Keep it up!
So, i have 200bx and its back looks like a porridge when it spawns and i then i need to repair it for 100 thousand dollars.
I just changing my money value to 100.000 and all is done. Idk if it happens to any other cars but thats how is it.
Ur insane, lucks!
upd: it happens SOMETIMES, not always.

**Comment by r3eckon** [comment]
Can you post a screenshot? Is this with enabled beamstate loading? Beamstate is disabled by default in the latest version because 0.28 advanced hinges broke the feature. I never experienced any issue with cars being damaged on spawn without beamstate enabled, if you aren't using beamstate it's possible another mod is causing issue so try a fresh install in a clean userfolder.

If you are using beamstate this is expected and nothing I can do about it. Devs have to fix beamstate loading.

**Comment by maksimkfive** [comment]
I guess beamstate was turned on. My apologies. BUT that aint all. I have another one for u.
Race opponents are ignoring the traffic and just hitting it.

**Comment by r3eckon** [comment]
Depends when and where, the AI can avoid traffic in some races but others are more difficult. I also noticed the AI decision making speed/quality seems to be tied to FPS so low FPS will make the AI worse. Again this is not something I can fix, this is all vanilla BeamNG quirks. Race AI is rarely used in combo with traffic in scenarios like this mod does so devs probably haven't been focusing on issues relating to this specific case.
