### ISSUE TITLE
Health disappeared? More suggestions.

### ISSUE THREAD

**Issue by abodyeasy** [r3eckon/BNG-BeamLegalRacing#8]
Hello, I really like the project so far, and I'm so excited for future updates, I'm sorry to put this on issues but I couldn't find anywhere else to put it, Anyways, I don't know if this is a problem or a bug but it seems that the health had disappeared? even if I crash so hard I don't die, If you're gonna add it in the next update, I have a suggestion for it, Since you can actually sleep to heal, why not add a medical center somewhere? where you can heal yourself for money (depending on the health loss), with No regeneration, only pay to heal, and for the sleeping part, maybe add a sleep score, if it reaches 0 you sleep automatically, if it's on 100, you can't sleep anymore, I love the new delivery update, I appreciate you adding it, For the calling a mechanic part, maybe make it so that when you're far away from the spawnpoint, it makes it more expensive to call a mechanic, for the repair damage, sometimes I crash and get some good dents but still the repair cost stays at $0.00, it would be nice if you make it like the older version where it calculates the constraints or whatever it was called, like 2323 = $23.23 but it would be nicer if you make it more expensive, that's about all, I'm sorry if that's the wrong way to post a suggestion, I'm very new to GitHub, keep up the good work reckon!

**Comment by r3eckon** [comment]
Health is disabled for now because vanilla G force sensors are bad in BeamNG, after crashing parts can wiggle which makes the game think the car is experiencing high G forces and drops health to 0 in seconds. I tried alternate G force calculation method that only had more issues than the vanilla one, so for now only instantly fatal crashes are still possible at very high G forces. Still G force sensor values are hardware dependent so the lower your FPS the harder it is to die because lag makes the game miss the simulation frame at which forces are highest.

Damage values are also vanilla and beam deformation used to calculate damage value isn't perfect. I can't use that directly because some configs spawn with damage and that would prevent changing parts or using them in events. 

Not sure I'll add forced sleep as I don't like this type of game mechanic but I'll keep the suggestion in mind for towing cost being distance based. And I'm glad you like the mod!
