### ISSUE TITLE
Vehicle disappears at spawn, gameplay frozen

### ISSUE THREAD

**Issue by rxn8** [r3eckon/BNG-BeamLegalRacing#9]
What I was doing:

Everything normal to start with. Opened the main game event menu, clicked Abandon to save game to backup. Game then entered a state where I had all the features of the main game, but the map config was still clearly BeamLR. Main menu still showed as BeamLR career mode as well, except choosing to abandon it now did nothing. Framerate dropped from ~100FPS to ~12FPS.

Restarted the game. Entered career mode once more, greeted with below screen. Could not move or look around despite trying multiple common controls. Playthrough over?

Attaching picture of career init screen; also see download link to my beamlr userfolder contents for diagnosis.

[In-game screen](https://i.imgur.com/UvQuJa6.jpg)

[Userfolder download link](https://mega.nz/file/ejxx1CCQ#uS1temXErxpsim77-HRjSdI05LIxiVHm4CmuDkwS5Ks)

**Comment by r3eckon** [comment]
Something happened during the save process when you clicked abandon that prevented the correct car data from being saved, also prevented the freeroam ui layout from being restored. The config files say the car is a covet but the main car file and beamstate files are for a burnside.

![](https://i.imgur.com/GaCxX9w.png)

![](https://i.imgur.com/w5Px796.png)

Not sure what might have caused this. Copy your backup folders somewhere else and do a clean reinstall in a userfolder without any other mods, carefully follow the instructions to ensure incorrect install isn't to blame. This mod can't be installed like a regular zip and has to be extracted inside the userfolder, usually file related issues can be caused by this. See if you can get the same problem again with the same steps after reinstalling. 

To fix the issue on your current files you need to replace "burnside" with "covet" inside the main vehicle file (beamLR/garage/car0) and then delete the beamstate file (beamLR/beamstate/car0.save.json) and it should spawn again, that being said the paint color might be different, also the odometer seems to be reset and the mechanical damage file seems to be empty which might cause issues again. One thing you can try if that doesn't work is buying a covet after clean reinstall and copy over the config file (beamLR/garage/config/car0) for your old covet.

**Comment by rxn8** [comment]
Thanks for checking this out. Luckily, I had a config of my BeamLR career car saved in my configs folder, so I copied that over to 0.29/beamLR/garage/config and replaced 'car0'. Loaded BeamLR successfully with my original burnside, dragged the car to the gas station to fill it up and all is normal.

The car0 file you were seeing and that I replaced appears to be my default game init config. Weird. At any rate, your suggested fix worked.
